apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cdi_runner_data_pvc.yaml
  - cdi_runner_wrgl_pvc.yaml
  - cdi_runner_dvc_cache_pvc.yaml
  - cdi_runner.yaml
