on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  apply-transaction:
    runs-on: cdi-runner
    steps:
      - name: Find transaction comment
        uses: peter-evans/find-comment@v2.0.0
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          body-includes: Review data changes at
          direction: last
      - name: Extract transaction url
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        id: txURL
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.fc.outputs.comment-body }}
          regex: |
            .+(https://hub\.wrgl\.co\/@.+)
          flags: "s"
          replacement: $1
      - name: Extract transaction id
        if: ${{ steps.txURL.outputs.value != null }}
        id: txid
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.txURL.outputs.value }}
          regex: .+\/tx\/(.+)
          flags: "" # Optional, defaults to "g"
          replacement: $1
      - name: Apply transaction
        if: ${{ steps.txid.outputs.value != null }}
        run: |
          cd /runner/_work/data
          echo "${KEYCLOAK_CLIENT_SECRET}" > secret.txt
          wrgl credentials authenticate https://wrgl.llead.co ipno-github secret.txt
          rm secret.txt
          yq e '.repos."https://wrgl.llead.co".relyingPartyToken' ${HOME}/.config/wrgl/credentials.yaml > token.txt
          echo "To https://wrgl.llead.co/transactions/${TXID}/"
          curl --fail -XPOST https://wrgl.llead.co/transactions/${TXID}/ \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $(cat token.txt)" \
          -d '{"commit":true}'
          rm token.txt
        env:
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          TXID: ${{ steps.txid.outputs.value }}
      - name: Create comment
        if: ${{ steps.txURL.outputs.value != null && steps.txid.outputs.value != null }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Transaction [tx/${{ steps.txid.outputs.value }}][1] applied.

            [1]: ${{ steps.txURL.outputs.value }}